{{- $redisHa := (index .Values "redis-ha") -}}
{{- if and .Values.redis.enabled (not $redisHa.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rss-hub.redis.fullname" . }}
  labels:
    {{- include "rss-hub.labels" . | nindent 4 }}
    {{- with .Values.redis.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.redis.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: redis
    port: {{ .Values.redis.servicePort }}
    targetPort: {{ .Values.redis.containerPort }}
  selector:
    {{- include "rss-hub.selectorLabels" . | nindent 4 }}
{{- end }}
