{{- if .Values.mercuryParser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttrss.mercuryParser.fullname" . }}
  labels:
    {{- include "ttrss.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mercuryParser.service.type }}
  ports:
    - port: {{ .Values.mercuryParser.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ttrss.mercuryParser.selectorLabels" . | nindent 4 }}
{{- end }}