{{- $redisHa := (index .Values "redis-ha") -}}
{{- if and .Values.redis.enabled (not $redisHa.enabled) .Values.redis.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rss-hub.redis.fullname" . }}-metrics
  {{- with .Values.redis.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "rss-hub.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name) | nindent 4 }}
    {{- with .Values.redis.metrics.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.redis.metrics.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: {{ .Values.redis.metrics.service.portName }}
      protocol: TCP
      port: {{ .Values.redis.metrics.service.servicePort }}
      targetPort: metrics
  selector:
    {{- include "rss-hub.selectorLabels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name) | nindent 4 }}
  type: {{ .Values.redis.metrics.service.type }}
{{- end }}
