{{- if and .Values.opencc.enabled .Values.opencc.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ttrss.opencc.fullname" . }}
  labels:
    {{- include "ttrss.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ttrss.opencc.fullname" . }}
  minReplicas: {{ .Values.opencc.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.opencc.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.opencc.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.opencc.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.opencc.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.opencc.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
